name: Deploy GetClassesFunction

on:
  push:
    paths:
      - 'backend/lambda/GetClasses/**'
      - '.github/workflows/deploy-get-classes.yml'
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda GetClasses
        run: |
          zip -j get_classes.zip backend/lambda/GetClasses/index.py
          aws lambda update-function-code \
            --function-name GetClassesFunction \
            --zip-file fileb://get_classes.zip